name: Terraform

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  Terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - uses: hashicorp/setup-terraform@v2
      
      - id: fmt
        name: Formatting for changed terraform files
        run: |
          git diff --name-only HEAD^
          # git diff --name-only HEAD^ | grep -i .tf$ | xargs -t -I % sh -c  '{ terraform fmt %; }'
      
      - id: check
        name: Check that a formatted terraform file exists
        run: echo "check=$(git status -s)" >> $GITHUB_OUTPUT
        
      - id: push
        name: Commit and push if formatted terraform files
        if: ${{ steps.check.outputs.check != '' }}
        run: |
          git config --global user.name "github-action"
          git config --global user.email "github-action@github.com"
          git add .
          git commit --amend --no-edit
          git push -f
