name: Terraform

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: read|write
  contents: read|write

jobs:
  Terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          
      - run: git pull ${{ github.base_ref }}

      - uses: hashicorp/setup-terraform@v2
      
      - run: git diff --name-only ${{ github.base_ref }} | xargs terraform fmt
      
      - name: check format
        id: check
        run: echo "check=$(git status -s)" >> $GITHUB_OUTPUT
        
      - run: |
          git config --global user.name "github-action"
          git config --global user.email "github-action@github.com"
          git add .
          git commit --amend --no-edit
          git push -f
        if: ${{ steps.check.outputs.check != '' }}
