name: Terraform

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  Terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - uses: hashicorp/setup-terraform@v2
      
      - run: terraform fmt -recursive
      
      - name: check format
        id: check
        run: echo "check=$(git status -s)" >> $GITHUB_OUTPUT
        
      - run: |
          echo check: ${{ steps.check.outputs.check }}
          echo check: ${{ steps.check.outputs.check != 0 }}
          echo check: ${{ steps.check.outputs.check != '' }}
          git config --global user.name "hashicorp"
          git config --global user.email "hello@hashicorp.com"
          git add .
          git commit --amend --no-edit
          git push -f
        if: ${{ steps.check.outputs != 0 }}
